# Generated by Django 5.2 on 2026-08-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in the URL: /work/<slug>', unique=True)),
                ('client', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('line', models.CharField(help_text='The one line under the title', max_length=240)),
                ('year', models.CharField(max_length=9)),
                ('sector', models.CharField(max_length=80)),
                ('disciplines', models.CharField(help_text='Comma separated: Social, Content, Analytics', max_length=200)),
                ('scope', models.CharField(help_text='Comma separated: Social strategy, Reporting', max_length=300)),
                ('brief', models.TextField(help_text='The situation')),
                ('approach', models.TextField(help_text='What we did')),
                ('outcome', models.TextField(help_text='The result')),
                ('card', models.ImageField(help_text='Image on the /work grid card', upload_to='work/')),
                ('hero', models.ImageField(help_text='Wide banner on the case study page', upload_to='work/')),
                ('thumb', models.ImageField(blank=True, help_text='Small thumb for the hero collage and next-project card. Falls back to the card image.', upload_to='work/')),
                ('start', models.PositiveSmallIntegerField(default=1, help_text='Column the card starts on, 1-12')),
                ('span', models.PositiveSmallIntegerField(default=6, help_text='How many columns wide')),
                ('row', models.PositiveSmallIntegerField(default=1)),
                ('off', models.PositiveSmallIntegerField(default=0, help_text='Vertical nudge in px, so a pair never reads as a tidy pair')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower shows first')),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='api.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 10,000+', max_length=40)),
                ('label', models.CharField(help_text='e.g. Followers in nine months', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
