# Generated by Django 5.2 on 2026-08-09 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(help_text='SVG, PNG, WebP or JPEG. Anything but SVG is compressed to WebP on save.', upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'webp', 'jpg', 'jpeg'])])),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower shows first')),
                ('published', models.BooleanField(default=True, help_text='Unpublishing removes it from both places')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CtaChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(default=100, help_text='Rendered size in px')),
                ('x', models.SmallIntegerField(help_text='Position across, % from the left')),
                ('y', models.SmallIntegerField(help_text='Position down, % from the top — may be negative')),
                ('rot', models.SmallIntegerField(default=0, help_text='Tilt in degrees')),
                ('order', models.PositiveIntegerField(default=0)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='api.logo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
