# Generated by Django 5.2 on 2026-08-09 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logo_ctachip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctachip',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Home page floating logo', 'verbose_name_plural': 'Home page floating logos'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Client logo', 'verbose_name_plural': 'Client logos'},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Extra image', 'verbose_name_plural': 'Extra images'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Result number', 'verbose_name_plural': 'Result numbers'},
        ),
        migrations.AlterField(
            model_name='ctachip',
            name='logo',
            field=models.ForeignKey(help_text='Pick from the client logos already uploaded. The same logo can be placed more than once — add another entry for each position.', on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='api.logo', verbose_name='Which logo'),
        ),
        migrations.AlterField(
            model_name='ctachip',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lowest number first. Only affects which is drawn on top when two overlap.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='ctachip',
            name='rot',
            field=models.SmallIntegerField(default=0, help_text='Tilt in degrees. A negative number leans left, positive leans right. Between -10 and 10 looks natural; more starts to look like a mistake.', verbose_name='Tilt'),
        ),
        migrations.AlterField(
            model_name='ctachip',
            name='size',
            field=models.PositiveSmallIntegerField(default=100, help_text='How large the logo appears, in pixels. The current ones range from 74 to 149. Larger logos read as closer to the viewer.', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='ctachip',
            name='x',
            field=models.SmallIntegerField(help_text='How far across the section, as a percentage. 0 is the far left edge, 100 the far right. Keep clear of 35 to 65 — the heading and button sit there.', verbose_name='Position across'),
        ),
        migrations.AlterField(
            model_name='ctachip',
            name='y',
            field=models.SmallIntegerField(help_text='How far down the section, as a percentage. 0 is the top edge, 100 the bottom. A negative number lifts it above the top edge so it is only partly visible.', verbose_name='Position down'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(help_text='SVG is best — it stays sharp at any size. Otherwise use a PNG with a transparent background. JPEGs work but will show a white box behind the logo. Large files are compressed for you.', upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'webp', 'jpg', 'jpeg'])], verbose_name='Logo file'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(help_text='Used to tell logos apart in this admin. It is not shown anywhere on the website.', max_length=120, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order logos appear in the sliding strip on the About page, lowest number first.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='published',
            field=models.BooleanField(default=True, help_text='Untick to remove this logo from the About page strip and from the home page, without deleting it.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approach',
            field=models.TextField(help_text='How you solved it. Two to four sentences.', verbose_name='What we did'),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief',
            field=models.TextField(help_text='What the client was facing before you started, and why it mattered. Two to four sentences.', verbose_name='The situation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='card',
            field=models.ImageField(help_text='The image for this project on the main work page. A landscape shape works best. Upload the best quality you have — it is compressed for you.', upload_to='work/', verbose_name='Card image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(help_text='The company the work was for, for example "VFD / Vbank". Shown in small type above the project title.', max_length=120, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disciplines',
            field=models.CharField(help_text='The kinds of work involved, separated by commas: Social, Content, Analytics. Each one becomes a small tag on the work page card.', max_length=200, verbose_name='Disciplines'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hero',
            field=models.ImageField(help_text="The wide image across the top of this project's own page. A very wide shape works best. Keep the important part near the middle: the banner is trimmed at the sides on a phone.", upload_to='work/', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='line',
            field=models.CharField(help_text='A single sentence shown under the title, roughly 8 to 14 words. For example "Roughly 100 followers to over 10,000 in nine months."', max_length=240, verbose_name='One-line summary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='off',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pushes the card further down its row, in pixels, so the two cards in a row do not line up in a neat pair. 0 to 150 is the usual range.', verbose_name='Drop down by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Projects are listed lowest number first. Ties are broken by whichever was added first.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcome',
            field=models.TextField(help_text='What changed for the client. One or two sentences — this is set in large type near the bottom of the page.', verbose_name='The result'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True, help_text='Untick to take this project off the website without deleting it.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='row',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which row down the page the card sits on. Two projects normally share a row, at different widths.', verbose_name='Row'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.CharField(help_text='What you actually delivered, separated by commas: Social strategy, Content production, Reporting. Appears in the facts list on the project page.', max_length=300, verbose_name='Scope of work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(help_text="The client's industry, for example Banking, FMCG or Legal. Appears in the facts list on the project page.", max_length=80, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='The last part of this project\'s web address. Entering "vfd" puts the page at /work/vfd. Lowercase letters and hyphens only, no spaces. Avoid changing it once the project is live — any link already shared will stop working.', unique=True, verbose_name='Page address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='span',
            field=models.PositiveSmallIntegerField(default=6, help_text='How many of the 12 columns the card fills. 6 is half the page width, 4 is a third. Starting column plus width should not go past 13.', verbose_name='Width in columns'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.PositiveSmallIntegerField(default=1, help_text='The work page is divided into 12 columns across. This is the column the card starts in: 1 is hard left, 12 is hard right.', verbose_name='Starts at column'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ImageField(blank=True, help_text='A small version used by the floating images at the top of the work page and by the "next project" link. Optional — the card image is used if you leave this empty, though a small, tightly cropped image looks better.', upload_to='work/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='The headline for this project, for example "A bank people talk about". Keep it short — it is set in very large type and long titles wrap awkwardly.', max_length=160, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(help_text='The year the work was delivered, for example 2024.', max_length=9, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='image',
            field=models.ImageField(help_text='An extra image shown further down the project page, below the writing.', upload_to='work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lowest number appears first.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(help_text='A short caption under the number, for example "Followers in nine months". Around three to five words.', max_length=80, verbose_name='What it means'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lowest number appears leftmost.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(help_text='The figure itself, for example "10,000+" or "100x" or "9 mo". It counts up when the visitor scrolls to it.', max_length=40, verbose_name='Number'),
        ),
    ]
