# Generated by Django 5.2 on 2026-08-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ctachip_options_alter_logo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The line a visitor sees before they open the row, for example "Community management". Keep it to a few words — it sits on one line.', max_length=160, verbose_name='Heading')),
                ('body', models.TextField(help_text='What is revealed when the row is opened. Two or three sentences. Plain text only — no headings or bullet points.', verbose_name='Details')),
                ('order', models.PositiveIntegerField(default=0, help_text='Rows are listed lowest number first.', verbose_name='Display order')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this row from the services page without deleting it.', verbose_name='Published')),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'Services page FAQ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
