# Generated by Django 5.2 on 2026-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('company', models.CharField(max_length=160, verbose_name='Company')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('received', models.DateTimeField(auto_now_add=True, verbose_name='Received')),
                ('sent', models.BooleanField(default=False, help_text='Ticked once the enquiry has been emailed on successfully.', verbose_name='Emailed')),
                ('error', models.TextField(blank=True, help_text='Why the email could not be sent, if it could not. The enquiry itself is still safely stored here.', verbose_name='Delivery error')),
            ],
            options={
                'verbose_name': 'Contact enquiry',
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-received'],
            },
        ),
    ]
