# Generated by Django 5.2 on 2026-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='A roughly square image works best — it is cropped to fill the frame. Upload the best quality you have; it is compressed for you.', upload_to='format/', verbose_name='Image')),
                ('alt', models.CharField(help_text='A short description for people using a screen reader, for example "Campaign film in production". Not shown on the page.', max_length=160, verbose_name='Describe the image')),
                ('order', models.PositiveIntegerField(default=0, help_text='The carousel runs lowest number first, then loops.', verbose_name='Display order')),
                ('published', models.BooleanField(default=True, help_text='Untick to drop this image from the carousel without deleting it.', verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Home page carousel image',
                'verbose_name_plural': 'Home page carousel',
                'ordering': ['order', 'id'],
            },
        ),
    ]
