# Generated by Django 5.2 on 2026-08-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Shown at a fixed height with the width left to follow, so portrait and landscape both sit happily in the row. Upload the best quality you have; it is compressed for you.', upload_to='gallery/', verbose_name='Image')),
                ('alt', models.CharField(help_text='A short description for people using a screen reader, for example "Shooting social content". Not shown on the page.', max_length=160, verbose_name='Describe the image')),
                ('order', models.PositiveIntegerField(default=0, help_text='The strip runs left to right, lowest number first.', verbose_name='Display order')),
                ('published', models.BooleanField(default=True, help_text='Untick to drop this image from the strip without deleting it.', verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Services page gallery',
                'ordering': ['order', 'id'],
            },
        ),
    ]
