# Generated by Django 5.2 on 2026-08-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='The year this happened, for example 2019. Milestones run oldest to newest, so this is what sets their order.', verbose_name='Year')),
                ('title', models.CharField(help_text='A few words, for example "One room in Lagos". Shown under the year.', max_length=120, verbose_name='Headline')),
                ('body', models.TextField(help_text='One or two sentences, revealed when this milestone is the active one.', verbose_name='What happened')),
                ('image', models.ImageField(help_text='Shown beside the text. A landscape shape works best. Upload the best quality you have; it is compressed for you.', upload_to='timeline/', verbose_name='Image')),
                ('alt', models.CharField(help_text='A short description for people using a screen reader. Not shown on the page.', max_length=160, verbose_name='Describe the image')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this milestone. Keep at least two published — the timeline scrolls between them and needs a start and an end.', verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Timeline milestone',
                'verbose_name_plural': 'About page timeline',
                'ordering': ['year', 'id'],
            },
        ),
    ]
