"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Defaults are the safe ones, so a missing variable fails closed rather than
# open. SECRET_KEY has none at all — no .env and Django refuses to boot.
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
)
# overwrite=True on purpose. This project shares a server with others, and a
# machine-wide variable set for one of them would otherwise silently win here —
# an inherited DATABASE_URL is enough to point this app at the wrong database.
# The .env sitting next to manage.py is the authority for this project.
ENV_FILE = BASE_DIR / ".env"
environ.Env.read_env(ENV_FILE, overwrite=True)


def _declared_in_env_file():
    """The keys the project's own .env actually sets, ignoring comments."""
    if not ENV_FILE.exists():
        return set()
    keys = set()
    for line in ENV_FILE.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip().removeprefix("export ")
        if line and not line.startswith("#") and "=" in line:
            keys.add(line.split("=", 1)[0].strip())
    return keys


# Overwriting only helps for keys the file actually declares. A key it leaves
# out is still inherited from the machine — which is how this app once pointed
# itself at another project's live database and created tables in it. Refuse to
# start instead, for the two that do real damage silently.
_declared = _declared_in_env_file()
for _key in ("DATABASE_URL", "SECRET_KEY"):
    if _key not in _declared and os.environ.get(_key):
        raise ImproperlyConfigured(
            f"{_key} is set machine-wide on this server (probably by another "
            f"project) but {ENV_FILE} does not declare it, so this app would "
            f"silently use the inherited value.\n\n"
            f"Add an explicit line to {ENV_FILE}. For DATABASE_URL, an empty "
            f"value means 'use the local sqlite file':\n\n"
            f"    {_key}=\n"
        )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    "rest_framework",
    "corsheaders",
    "api",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # serves everything in STATIC_ROOT, so the admin keeps its styling without
    # IIS needing a virtual directory for /static/. Must sit directly after
    # SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Empty when the site and API share a domain, which is the case once IIS serves
# both — the browser never makes a cross-origin request, so there is nothing to
# allow. The filter stops a blank .env line becoming a [''] entry.
CORS_ALLOWED_ORIGINS = [o for o in env("CORS_ALLOWED_ORIGINS") if o]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Contact form. The Graph app sends as MS_GRAPH_SENDER using the client
# credentials flow — no mailbox password involved.
MS_GRAPH_TENANT_ID = env("MS_GRAPH_TENANT_ID", default="")
MS_GRAPH_CLIENT_ID = env("MS_GRAPH_CLIENT_ID", default="")
MS_GRAPH_CLIENT_SECRET = env("MS_GRAPH_CLIENT_SECRET", default="")
MS_GRAPH_SENDER = env("MS_GRAPH_SENDER", default="")
CONTACT_RECIPIENT = env("CONTACT_RECIPIENT", default="")

REST_FRAMEWORK = {
    # the contact endpoint is the only public write on the API, so it is the
    # only thing that needs a ceiling
    "DEFAULT_THROTTLE_RATES": {"contact": "12/hour"},
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Empty means the local sqlite file. Set DATABASE_URL to a postgres:// URL to
# move (needs `pip install "psycopg[binary]"`).
#
# Read as a plain string first rather than letting env.db_url fall back on its
# own: an empty value has to mean "sqlite", so that .env can blank out a
# DATABASE_URL inherited from another project on the same machine.
_database_url = env("DATABASE_URL", default="")
DATABASES = {
    "default": env.db_url_config(_database_url) if _database_url else {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Times are always stored in UTC; this only controls how they read in the admin.
# Set TIME_ZONE=Africa/Lagos so enquiry timestamps match the studio's clock.
TIME_ZONE = env("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Where `manage.py collectstatic` gathers the admin's own CSS and JS ready to be
# served. Without this the admin renders unstyled once DEBUG is off.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise compresses each file and stamps a hash into its name, so static
# assets can be cached forever and still update the moment they change.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Uploaded images. Django has no production-grade media server, so ideally IIS
# maps /media/ straight at MEDIA_ROOT as a virtual directory and this stays off.
# Left on by default so a fresh deployment shows its images before that is set
# up; turn it off once IIS is serving them.
SERVE_MEDIA = env.bool("SERVE_MEDIA", default=True)

# The localhost port waitress listens on, proxied to by IIS. Only needs changing
# if something else on the machine already holds it — another Django app very
# often does. Change it here and in the matching line of frontend/public/web.config.
BACKEND_PORT = env.int("BACKEND_PORT", default=8000)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Security. Every one of these is a no-op in development and matters the moment
# the site is on a real domain, so each defaults to "off while DEBUG, on after".
# Django's own audit is `manage.py check --deploy`.

# The domains the admin login form may be posted from. Django rejects a login
# over HTTPS from an origin not listed here, so this is required, not optional.
CSRF_TRUSTED_ORIGINS = [o for o in env.list("CSRF_TRUSTED_ORIGINS", default=[]) if o]

SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)

# Tells Django a request was HTTPS when a proxy terminated the TLS. Without it,
# SECURE_SSL_REDIRECT behind a load balancer becomes an infinite redirect loop.
if env.bool("BEHIND_PROXY", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Left off deliberately. HSTS tells browsers to refuse plain HTTP for this
# domain for the given period, and it cannot be undone early — turn it on only
# once HTTPS is confirmed working on every subdomain. 31536000 is one year.
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
